export const data = [
    {id:1, name: 'Nguyễn Văn A', dateOfbirth: '28/02/1990', email: 'nvana@gmail.com', address:'Ba Đình, Hà Nội', status: true},
    {id:2, name: 'Trần Thị B', dateOfbirth: '15/07/1985', email: 'ttb@gmail.com', address:'Cầu Giấy, Hà Nội', status: false},
    {id:3, name: 'Lê Văn C', dateOfbirth: '03/10/2000', email: 'lvc@gmail.com', address:'	Hai Bà Trưng, Hà Nội', status: false},
    {id:4, name: 'Phạm Thị D', dateOfbirth: '20/05/1995', email: 'ptd@gmail.com', address:'Hoàn Kiếm, Hà Nội', status: true},
    {id:5, name: 'Ngô Văn E', dateOfbirth: '12/11/1988', email: 'nve@gmail.com', address:'Cầu Giấy, Hà Nội', status: true},
    {id:6, name: 'Nguyễn Văn F', dateOfbirth: '28/02/1990', email: 'nvana@gmail.com', address:'Ba Đình, Hà Nội', status: true},
    {id:7, name: 'Trần Thị G', dateOfbirth: '15/07/1985', email: 'ttb@gmail.com', address:'Cầu Giấy, Hà Nội', status: false},
    {id:8, name: 'Lê Văn H', dateOfbirth: '03/10/2000', email: 'lvc@gmail.com', address:'	Hai Bà Trưng, Hà Nội', status: false},
    {id:9, name: 'Phạm Thị I', dateOfbirth: '20/05/1995', email: 'ptd@gmail.com', address:'Hoàn Kiếm, Hà Nội', status: true},
    {id:10, name: 'Ngô Văn J', dateOfbirth: '12/11/1988', email: 'nve@gmail.com', address:'Cầu Giấy, Hà Nội', status: true},
    {id:11, name: 'Nguyễn Văn K', dateOfbirth: '28/02/1990', email: 'nvana@gmail.com', address:'Ba Đình, Hà Nội', status: true},
    {id:12, name: 'Trần Thị L', dateOfbirth: '15/07/1985', email: 'ttb@gmail.com', address:'Cầu Giấy, Hà Nội', status: false},
    {id:13, name: 'Lê Văn M', dateOfbirth: '03/10/2000', email: 'lvc@gmail.com', address:'	Hai Bà Trưng, Hà Nội', status: false},
    {id:14, name: 'Phạm Thị N', dateOfbirth: '20/05/1995', email: 'ptd@gmail.com', address:'Hoàn Kiếm, Hà Nội', status: true},
    {id:15, name: 'Ngô Văn O', dateOfbirth: '12/11/1988', email: 'nve@gmail.com', address:'Cầu Giấy, Hà Nội', status: true},
    {id:16, name: 'Nguyễn Văn P', dateOfbirth: '28/02/1990', email: 'nvana@gmail.com', address:'Ba Đình, Hà Nội', status: true},
    {id:17, name: 'Trần Thị Q', dateOfbirth: '15/07/1985', email: 'ttb@gmail.com', address:'Cầu Giấy, Hà Nội', status: false},
    {id:18, name: 'Lê Văn T', dateOfbirth: '03/10/2000', email: 'lvc@gmail.com', address:'	Hai Bà Trưng, Hà Nội', status: false},
    {id:19, name: 'Phạm Thị U', dateOfbirth: '20/05/1995', email: 'ptd@gmail.com', address:'Hoàn Kiếm, Hà Nội', status: true},
    {id:20, name: 'Ngô Văn V', dateOfbirth: '12/11/1988', email: 'nve@gmail.com', address:'Cầu Giấy, Hà Nội', status: true}
]